# site name
prefixName: a154051
siteName: 
# favicon and site master avatar
favicon: /images/chess-king.svg
avatar: /img/头像new.jpg
url: https://a154051.gitee.io/
description: 菜就多练练
cdn: https://cdn.jsdelivr.net/gh/154051/cdn@master
pjax: 1
# 1开启
mathjax: 1
# mathjax: true
notice: 欢迎来到我的博客
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-home faa-wrench }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    题解: {path: /categories/题解/, fa: fa-code },
    笔记: {path: /categories/笔记/, fa: fa-book },
  } }
  tags: { path: /tags/, fa: fa-list-ul faa-vertical }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  # 番剧: {path: /bangumi/, fa: fa-film faa-vertical }
  # 歌单: {path: /music/, fa: fa-headphones }
  # 游戏: {path: /games/, fa: fa-gamepad}
  关于: { path: /theme-sakura/, fa: fa-leaf faa-wrench }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/154051/cdn@master/img/星月夜new.jpg
  - https://cdn.jsdelivr.net/gh/154051/cdn@master/img/cover2new.jpg
  - https://cdn.jsdelivr.net/gh/154051/cdn@master/img/cover1new.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/165723104, title: Bilibili, desc: 博主的b站账号, img: /img/startdash/bilibili.jpg}
  - {url: https://www.luogu.com.cn/user/347122, title: 洛谷, desc: 本蒟蒻的洛谷, img: /img/空白new.jpg}



# your site build time or founded date
siteBuildingTime: 04/12/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/154051, img: /img/social/github.png}
  #email: {url: 2279162137@qq.com, img: /img/social/email.svg}
  bilibili: {url: https://space.bilibili.com/165723104, img: /img/social/bilibili.png}
  洛谷: {url: https://www.luogu.com.cn/user/347122, img: /img/social/luogu.jpg}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  #wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/154051, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: none
  volume: 0.7
  mutex: true

# Valine
valine: false
v_appId: rNY2a0do2F5IkY1hjVtYCYEw-MdYXbMMI
v_appKey: AK8kkYPveMhsDMtYFXRUSHgo

twikoo:
  enable: true
  envId: https://tranquil-centaur-0714bb.netlify.app/.netlify/functions/twikoo

# 简易信息聚合,站点共享
rss: /atom.xml